<?xml version="1.0"?>
<robot name="turtle_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- Get the path to the yaml file relative to the package -->
<!-- config.yaml should have been installed in setup.py -->
<xacro:property name="yaml_file" value="$(find turtle_brick)/turtle.yaml" />
<!-- load values from yaml file which are stored in a dictionary called props-->
<xacro:property name="props" value="${xacro.load_yaml(yaml_file)['/**']['ros__parameters']}" />
<!-- access an individual variable -->
<xacro:property name="platform_height"  value="${props['platform_height']}" />
<xacro:property name="wheel_radius"  value="${props['wheel_radius']}" />
<!-- <xacro:property name="max_velocity"  value="${props['max_velocity']}" />
<xacro:property name="gravity_accel"  value="${props['gravity_accel']}" /> -->
<!-- <xacro:property name="base_link_origin"  value="${}" /> -->


  <link name="base_link">
    <visual>
      <origin xyz="0 0 0.5" rpy="0 0 0"/> 
      <geometry>
        <box size="${platform_height / (platform_height*2)} ${platform_height / (platform_height*2)} ${platform_height / (platform_height*2)}"/>
      </geometry>
      <material name="White">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
  </link>

  <link name="platform">
    <visual>
      <origin xyz="0 0 ${platform_height}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${platform_height/10}" radius="0.7"/>
      </geometry>
      <material name="Red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
  </link>


  <link name="pole">
    <visual>
      <origin xyz="0 0 1" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${platform_height}" radius="0.03"/>
      </geometry>
      <material name="Blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
  </link>

  <link name="wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
          <material name="Yellow">
            <color rgba="1.0 1.0 0.0 1.0"/>
          </material>
    </visual>
  </link>

  <link name="stem">
    <visual>
      <origin xyz="0 0 0.3" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.5" radius="0.02"/>
      </geometry>
      <material name="Green">
        <color rgba="0 1 0 1"/>
      </material>
    </visual>
  </link>

  <joint name="j1" type="fixed">
    <axis xyz="0 0 1" />
    <origin xyz="0 0 0"/>
    <parent link="base_link"/>
    <child link="stem"/>
  </joint>

  <joint name="j2" type="fixed">
    <axis xyz="1 0 0" />
    <origin xyz="0 0 0"/>
    <parent link="stem"/>
    <child link="wheel"/>
  </joint>

  <joint name="j3" type="fixed">
    <axis xyz="1 0 0" />
    <origin xyz="0 0 0"/>
    <parent link="pole"/>
    <child link="platform"/>
  </joint>

  <joint name="base_to_pole" type="fixed">
    <origin xyz="0 0 0" />
    <parent link="base_link"/>
    <child link="pole"/>
  </joint>
  
</robot>
